image: node:18.15.0

cache:
  paths:
    - node_modules

stages:
  - build
  - deploy

before_script:
  - npm install

build-job:
  stage: build
  only:
    - master
  script:
    - npm run build
  artifacts:
    paths:
      - node_modules

deploy-job:
  stage: deploy
  only:
    - master
  script:
    - npm run start

