image: node:18.15.0

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build-job:
  stage: build
  only:
    - master
  script:
    - node -v
    - npm -v
    - npm install
    - npm run build
  artifacts:
    paths:
      - /home/gitlab-runner/

deploy-job:
  stage: deploy
  only:
    - master
  script:
    - npm run start
