image: node:18.15.0

stages:
  - build
  - build-image

build-app-job:
  stage: build
  only:
    - master
  script:
    - npm install
    - npm run build

build-image-job:
  stage: build-image
  only:
    - master
  script:
    - docker-compose build
    - docker-compose up
