default:
  image: node:18.15.0

  services:
    - mysql:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build-job:
  stage: build
  only:
    - master
  script:
    - npm install
    - npm run build

deploy-job:
  stage: deploy
  only:
    - master
  script:
    - npm run start
