stages:
  - build
  - deploy

build-job:
  image: node:18.15.0
  stage: build
  only:
    - master
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - /home/gitlab-runner/

deploy-job:
  image: gitlab/dind
  stage: deploy
  services:
    - docker:dind
  only:
    - master
  script:
    - npm run start
