image: node:18.15.0

stages:
  - build
  - deploy

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm//

build-job:
  stage: build
  only:
    - master
  script:
    - npm install
    - npm run build

deploy-job:
  stage: deploy
  only:
    - master
  script:
    - npm run start
