image: node:18.15.0

cache:
  paths:
    - node_modules/

stages:
  - build

build-job:
  stage: build
  only:
    - master
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - /home/gitlab-runner/
