### Добавить специальность
POST http://localhost:8000/specialization
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJuYWlsMDEwMiIsInJvbGVzIjpbeyJpZCI6MSwidmFsdWVzIjoiVVNFUiIsImRlc2NyaXB0aW9uIjoiVXNlciIsImNyZWF0ZWRBdCI6IjIwMjMtMDEtMDFUMDA6MDA6MDAuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjMtMDEtMDFUMDA6MDA6MDAuMDAwWiIsIlVzZXJSb2xlIjp7ImlkIjo0LCJyb2xlSWQiOjEsInVzZXJJZCI6M319LHsiaWQiOjIsInZhbHVlcyI6IkFETUlOIiwiZGVzY3JpcHRpb24iOiJBZG1pbiIsImNyZWF0ZWRBdCI6IjIwMjMtMDEtMDFUMDA6MDA6MDAuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjMtMDEtMDFUMDA6MDA6MDAuMDAwWiIsIlVzZXJSb2xlIjp7ImlkIjozLCJyb2xlSWQiOjIsInVzZXJJZCI6M319XSwiaWF0IjoxNjg2MTU3MTE1LCJleHAiOjE2ODYyNDM1MTV9.-RTemgHIf6VH1EkH6g73L2lFMRe6iYiiz-24CzIy4Yo

{
  "num": "08.02.08",
  "name": "\"Монтаж и эксплуатация оборудования и систем газоснабжения\", техник",
  "period_year": 3,
  "period_month": 10,
  "budget": true,
  "num_place": 50
}

### Обновить
POST http://localhost:8000/specialization/1
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJuYWlsMDEwMiIsInJvbGVzIjpbeyJpZCI6MSwidmFsdWVzIjoiVVNFUiIsImRlc2NyaXB0aW9uIjoiVXNlciIsImNyZWF0ZWRBdCI6IjIwMjMtMDEtMDFUMDA6MDA6MDAuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjMtMDEtMDFUMDA6MDA6MDAuMDAwWiIsIlVzZXJSb2xlIjp7ImlkIjo0LCJyb2xlSWQiOjEsInVzZXJJZCI6M319LHsiaWQiOjIsInZhbHVlcyI6IkFETUlOIiwiZGVzY3JpcHRpb24iOiJBZG1pbiIsImNyZWF0ZWRBdCI6IjIwMjMtMDEtMDFUMDA6MDA6MDAuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjMtMDEtMDFUMDA6MDA6MDAuMDAwWiIsIlVzZXJSb2xlIjp7ImlkIjozLCJyb2xlSWQiOjIsInVzZXJJZCI6M319XSwiaWF0IjoxNjg2MDU4MDkzLCJleHAiOjE2ODYxNDQ0OTN9.vTnss5R7mOdnzanHFk8mq-Q2BXmMkPmkhXtBZl1khXQ

{
  "name": "высшее заборостроение"
}

### Получить все специальности
GET http://localhost:8000/specialization
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJuYWlsMDEwMiIsInJvbGVzIjpbeyJpZCI6MSwidmFsdWVzIjoiVVNFUiIsImRlc2NyaXB0aW9uIjoiVXNlciIsImNyZWF0ZWRBdCI6IjIwMjMtMDEtMDFUMDA6MDA6MDAuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjMtMDEtMDFUMDA6MDA6MDAuMDAwWiIsIlVzZXJSb2xlIjp7ImlkIjo0LCJyb2xlSWQiOjEsInVzZXJJZCI6M319LHsiaWQiOjIsInZhbHVlcyI6IkFETUlOIiwiZGVzY3JpcHRpb24iOiJBZG1pbiIsImNyZWF0ZWRBdCI6IjIwMjMtMDEtMDFUMDA6MDA6MDAuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjMtMDEtMDFUMDA6MDA6MDAuMDAwWiIsIlVzZXJSb2xlIjp7ImlkIjozLCJyb2xlSWQiOjIsInVzZXJJZCI6M319XSwiaWF0IjoxNjg2MDU4MDkzLCJleHAiOjE2ODYxNDQ0OTN9.vTnss5R7mOdnzanHFk8mq-Q2BXmMkPmkhXtBZl1khXQ
